# site properties and page defaults
title: "Next generation Energy Materials & Electrochemistry Lab."
author: "nemelab"
show-subtitle : false
subtitle: NEME
description: "neme, nemelab, 배터리, 배터리 연구실, 광운대학교, 김민경 교수님"
header: images/background.jpg
footer: images/background.jpg
proofer: false

# site social media and other links
links:
  email: contact@nemelab.com
  orcid: 0000-0001-8713-9213
  google-scholar: ETJoidYAAAAJ
  github: nemelab
  twitter: nemelab
  youtube: nemelab

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
      description: "neme, nemelab, 김민경교수님, 배터리 연구실, 광운대학교"
      keywords: [neme, nemelab, 김민경교수님, 배터리 연구실]
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true
  projects:
    output: true

# jekyll plugins
url: "https://nemelab.github.io"
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at
  - jekyll-seo-tag

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
