#- id: doi:10.1371/journal.pcbi.1007128
#  type: paper
#  description: Lorem ipsum _dolor_ **sit amet**, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
#  date: 2020-12-4
#  image: https://journals.plos.org/ploscompbiol/article/figure/image?size=inline&id=info:doi/10.1371/journal.pcbi.1007128.g001&rev=2
#  buttons:
#    - type: manubot
#      link: https://greenelab.github.io/meta-review/
#    - type: source
#      text: Manuscript Source
#      link: https://github.com/greenelab/meta-review
#    - type: website
#      link: http://manubot.org/
#  tags:
#    - open sciencedd
#    - collaborationdd
# ddddd repo: greenelab/meta-reviewdddd ddddddddddddd

- title: Suppressing Surface and Bulk Degradation of Single-Crystal LiNiO2 through Additive-Driven Interfacial Stabilization
  authors:
    - "_**Sooyeon Choi**_"
    - "**Minkyung Kim***"
  description: **(Accepted)**
  publisher: Chemical Engineering Journal
  date: 2025-09-11
  image: https://ars.els-cdn.com/content/image/X13858947.jpg

- title: Enhancing Cycle Stability in LiNiO2 with Phase transition suppression via Crystalline Disordered Surface Layer
  authors:
    - "_**Sooyeon Choi#**_"
    - "_**Dong-hee Lee#**_"
    - "**Yonghyeon Kwon**"
    - Maxim Avdeev, Seok Hyun Song, Minki Kim, Sehyun Kim, Seung-yong Lee, Hyungsub Kim
    - "**Minkyung Kim***"
  description: _(# Equally contribuited)_
  publisher: Advanced Science
  date: 2025-07-18
  link: https://doi.org/10.1002/advs.202503476
  image: https://advanced.onlinelibrary.wiley.com/cms/asset/53c91a8f-8f45-4cc7-989b-973d636f1711/advs70938-fig-0005-m.jpg
  id: doi:10.1002/advs.202503476

- id: doi:10.1002/advs.201500366
  authors:
    - "**Minkyung Kim**"
    - Seongsu Lee
    - Byoungwoo Kang*
  image: https://advanced.onlinelibrary.wiley.com/cms/asset/826e7547-bb6a-414e-9b86-0df6cbb19c1b/advs92-fig-0006-m.png

- id: doi:10.1021/acsaem.0c02278
  authors:
    - "**Minkyung Kim**"
    - Jian Zhu, Linze Li, Chongmin Wang, Guoying Chen*
  image: https://pubs.acs.org/cms/10.1021/acsaem.0c02278/asset/images/medium/ae0c02278_0008.gif

- id: doi:10.1021/acs.chemmater.7b00124
  authors:
    - "**Minkyung Kim**"
    - Seongsu Lee, Byoungwoo Kang*
  image: https://pubs.acs.org/cms/10.1021/acs.chemmater.7b00124/asset/images/medium/cm-2017-00124f_0008.gif

- id: doi:10.1039/D2TA02492F
  authors:
    - "**Minkyung Kim**"
    - Lianfeng Zou, Seoung-Bum Son, Ira D. Bloom, Chongmin Wang, Guoying Chen*
  image: https://pubs.rsc.org/image/article/2022/TA/d2ta02492f/d2ta02492f-f1.gif

- id: doi:10.1039/D1TA10459D
  authors:
    - Jong Hyeong Lim, Jong Ho Won, Mun Kyoung Kim, Dae Soo Jung
    - "**Minkyung Kim**"
    - Chulhwan Park, Sang-Mo Koo, Jong-Min Oh, Hyung Mo Jeong
    - Hiesang Sohn\*
    - Weon Ho Shin\*
  image: https://pubs.rsc.org/image/article/2022/TA/d1ta10459d/d1ta10459d-f1.gif

- id: doi:10.1016/j.joule.2019.01.002
  authors:
    - Minkyu Kim, Donghoon Kim, Yuren Wen
    - "**Minkyung Kim**"
    - Hyun Myung Jang, Hong Li, Lin Gu, Byoungwoo Kang*
  image: https://www.cell.com/cms/10.1016/j.joule.2019.01.002/asset/bbbad183-d97c-4a8f-9213-dfe44602ded8/main.assets/gr6_lrg.jpg

- id: doi:10.1039/D0EE02518F
  authors:
    - "**Minkyung Kim**"
    - Mihee Jeong, Won-Sub Yoon, Byoungwoo Kang*
  image: https://pubs.rsc.org/image/article/2020/EE/d0ee02518f/d0ee02518f-f1.gif

- id: doi:10.1002/aenm.201800298
  authors:
    - Minkyu Kim
    - "**Minkyung Kim**"
    - Heetaek Park, Hong Li, Byoungwoo Kang*
  image: https://advanced.onlinelibrary.wiley.com/cms/asset/bd3b2bc4-c3e3-4981-ab5d-8cc43ec40a78/aenm201800298-fig-0001-m.jpg

- id: doi:10.1002/adfm.202109759
  authors:
    - Yongjo Jung, Seoungkyu Park, Jin Kon Kim
    - "**Minkyung Kim***"
    - Byoungwoo Kang\*
  image: https://advanced.onlinelibrary.wiley.com/cms/asset/bd169da4-7c1e-4369-a3c0-07d35a488b5e/adfm202109759-fig-0001-m.png

- id: doi:10.1021/acsenergylett.9b02451
  authors:
    - "**Minkyung Kim**"
    - Maxim Avdeev, Byoungwoo Kang*
  image: https://pubs.acs.org/cms/10.1021/acsenergylett.9b02451/asset/images/medium/nz9b02451_0006.gif

- id: doi:10.3390/ma15062284
  authors:
    - Yong-Jae Jung, Hyun-Sik Kim, Jong Ho Won
    - "**Minkyung Kim**"
    - Minji Kang, Eun Young Jang, Nguyen Vu Binh, Sang-il Kim, Kyoung-Seok Moon, Jong Wook Roh, Woo Hyun Nam, Sang-Mo Koo, Jong-Min Oh
    - Jung Young Cho\*
    - Weon Ho Shin\*
  image: https://www.mdpi.com/materials/materials-15-02284/article_deploy/html/images/materials-15-02284-g002-550.jpg

- id: doi:10.1039/C9TA03070K
  authors:
    - Heetaek Park
    - "**Minkyung Kim**"
    - ShinYoung Kang\*
    - Byoungwoo Kang\*
  image: https://pubs.rsc.org/image/article/2019/TA/c9ta03070k/c9ta03070k-f8.gif

- id: doi:10.3390/ma15124283
  authors:
    - Da-Eun Hyun, Jwa-Bin Jeon, Yeon-Sook Lee, Yong-Nam Kim
    - "**Minkyung Kim**"
    - Seunghoon Ko, Sang-Mo Koo, Weon Ho Shin, Chulhwan Park
    - Dong-Won Lee\*
    - Jong-Min Oh\*
  image: https://www.mdpi.com/materials/materials-15-02284/article_deploy/html/images/materials-15-02284-g001-550.jpg

- id: doi:10.1149/1945-7111/ad51a9
  authors:
    - "**Changyu Yeo**"
    - "**Minkyung Kim***"
  image: https://content.cld.iop.org/journals/1945-7111/171/6/060511/revision2/jesad51a9f1_lr.jpg

- id: doi:10.1016/j.jmrt.2023.03.024
  authors:
    - Hyung-Jin Lee, Soo-Young Moon, Hee-Jae Lee, Dong-Wook Byun, Seung-Woo Jung, Michael A. Schweitz
    - "**Minkyung Kim**"
    - Jong-Min Oh, Weon Ho Shin, Chulhwan Park, Sang-Mo Koo*
  image: https://ars.els-cdn.com/content/image/1-s2.0-S223878542300488X-gr1.jpg

- id: doi:10.1016/j.jpowsour.2022.231692
  authors:
    - Doyoub Kim, Heetaek Park, Maxim Avdeev
    - "**Minkyung Kim***"
    - Byoungwoo Kang\*
  image: https://ars.els-cdn.com/content/image/1-s2.0-S0378775322006899-gr3.jpg

- id: doi:10.1002/advs.202410114
  authors:
    - "_**Chiwon Choi#**_"
    - "_**Hyunmin Yoon#**_"
    - Seungyeop Kang, Dong Il Kim, John Hong, Minjeong Shin, Dong-Joo Yoo
    - "**Minkyung Kim***"
  description: _(# Equally contribuited)_
  image: https://advanced.onlinelibrary.wiley.com/cms/asset/20973892-a729-44de-9d81-a459e99f1b79/advs9942-fig-0005-m.png

- id: doi:10.1021/acsaem.3c00275
  authors:
    - "**Dong-hee Lee**"
    - Maxim Avdeev, Dong-il Kim, Weon Ho Shin, John Hong
    - "**Minkyung Kim***"
  image: https://pubs.acs.org/cms/10.1021/acsaem.3c00275/asset/images/medium/ae3c00275_0007.gif
